[package]
name = "tiled-amethyst-example"
version = "0.1.0"
authors = []

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", rev = "f8aafa290a2ce82efcae49f11363ebebdbcfa974" }
tiled = "0.8.0"